name: Bheem Module CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Show project structure
        run: |
          echo "✅ Bheem module is setup."
          ls -la
